### ISSUE TITLE
Why do you use WebSockets and streams instead of HTTP and files?

### ISSUE THREAD

**Issue by metamaker** [Cognigy/CognigyClient#3]
If I send to cloud TTS something like "Hi, my name is Mark", I expect that when I send same text second time, I will receive same output. Therefore it is logical to have the output of TTS as some cached resource.

The question is: why would I need to receive audio stream instead of audio file as result of request?

Audio stream chunks can be compressed by gzip, sure, but quality of compression will be much lower if to compare with compression of complete audio file (e.g. mp3 or other lossy, but dense compression).

Largest advantage of files would be possibility to cache compressed TTS results, so system becomes more scalable. No need to recalculate speech on every request.

You will need to write less code for reliability. If Internet connection has gone down, you won't need to worry about recalculation of stream or reestablishing connection with server side, since this is already implemented by any static content server.

The only scenario that I can think of when streams are better than complete files is real-time speech synthesis, but as far as I know, this kind of TTS usually produces worse results (bcz TTS system doesn't have semantic context that complete sentence or paragraph can provide).

https://stackoverflow.com/questions/35785480/playing-audio-without-audio-tag
https://blogs.windows.com/buildingapps/2016/03/14/when-to-use-a-http-call-instead-of-a-websocket-or-http-2-0/#y2z4c6YpVUih8Axh.97

**Comment by metamaker** [comment]
Ok, I originally missed the concept of what this product should do. Issue closed.

**Comment by mayrbenjamin92** [comment]
Hi metamaker, sorry for the late response. We are an enterprise-software company building a middle-ware to implement speech-technology/language-technology into large companies software products.

The cognigy brain (cognigy AI) is a software product that allows you to interact with language and to build interactive dialogs. The "CognigyClient", which is the source you can find in this repo, is one of our possibilities to connect to the "cognigy AI"-server to send and retrieve text/data.

Since our AI-system produces a large variety of different outputs - even for the same input! - an additional caching layer does currently make no sense for it.

For more information you can visit us online:
http://www.cognigy.com/
